---

- name: Install CentOS RPM 
  yum:
    name: "https://s3.us-east-1.com/amazon-ssm-us-east-1/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present

- include_tasks: register.yml
  when: aws_ssm_activation_code is defined and aws_ssm_activation_id is defined
